### ISSUE TITLE
tabinvmodifier import error

### ISSUE THREAD

**Issue by filefolder** [SeisComP/extras#4]
Having trouble getting this to work in sc4. Default interpreter is py2 which gives

```
$ seiscomp exec tabinvmodifier
Traceback (most recent call last):
  File "/Rdata/seiscomp/bin/tabinvmodifier", line 19, in <module>
    from nettab.basesc3 import sc3
  File "/Rdata/seiscomp/lib/python/nettab/basesc3.py", line 2, in <module>
    import seiscomp.datamodel, seiscomp.core, seiscomp.config
  File "/Rdata/seiscomp/lib/python/seiscomp/datamodel.py", line 13, in <module>
    from . import _datamodel
ImportError: dynamic module does not define init function (init_datamodel)

```

Not sure if intentional. Changing this to py3 gives

```
$ seiscomp exec tabinvmodifier
Traceback (most recent call last):
  File "/Rdata/seiscomp/bin/tabinvmodifier", line 18, in <module>
    from nettab.lineType import Nw, Sa, Na, Ia
  File "/Rdata/seiscomp/lib/python/nettab/lineType.py", line 7, in <module>
    from helpers import parsers
ModuleNotFoundError: No module named 'helpers'
```

installed "helpers" but then helpers cannot import name 'parsers'...

**Comment by andres-h** [comment]
Fixed this issue. Not sure these tools work properly with Python 3 yet, but please give it another try.

**Comment by filefolder** [comment]
Thanks! Runs and updates as expected. Closing
